plugins {
  id 'java'
}

jar {
  enabled = true
}

dependencies {
  implementation 'jakarta.validation:jakarta.validation-api:3.1.1'
  implementation 'org.hibernate.validator:hibernate-validator:9.0.1.Final'
  testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
  testImplementation 'org.junit.jupiter:junit-jupiter-api:5.12.2'
  testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.12.2'
}