plugins {
  id 'java'
  id 'org.springframework.boot' version '3.5.4'
  id 'io.spring.dependency-management' version '1.1.7'
}

repositories {
  mavenCentral()
}
tasks.bootJar { enabled = false }
tasks.jar { enabled = true }

dependencies {
  implementation project(':domain')
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
  testImplementation('org.springframework.boot:spring-boot-starter-test')
  testImplementation 'com.h2database:h2'
  implementation 'org.hibernate.validator:hibernate-validator:9.0.1.Final'
  implementation "org.glassfish:jakarta.el:4.0.0"

}

test {
  useJUnitPlatform()
}